// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASXaY-36shfdesVxpQdViJRTUleD8Ev3o',
    appId: '1:1042179262286:web:9cf3fe8570d07e1000801f',
    messagingSenderId: '1042179262286',
    projectId: 'homzes-e3fa3',
    authDomain: 'homzes-e3fa3.firebaseapp.com',
    storageBucket: 'homzes-e3fa3.firebasestorage.app',
    measurementId: 'G-M1QX1PZ2ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAZevqtmnAWI_cl-cNe4XVST6y8FHom_k',
    appId: '1:1042179262286:android:c8c900151abec38400801f',
    messagingSenderId: '1042179262286',
    projectId: 'homzes-e3fa3',
    storageBucket: 'homzes-e3fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH-lu-7ulkjFLo94B3QKimaL4oEHU-p9M',
    appId: '1:1042179262286:ios:0c951ef5ba71b30f00801f',
    messagingSenderId: '1042179262286',
    projectId: 'homzes-e3fa3',
    storageBucket: 'homzes-e3fa3.firebasestorage.app',
    iosBundleId: 'com.example.homzesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH-lu-7ulkjFLo94B3QKimaL4oEHU-p9M',
    appId: '1:1042179262286:ios:0c951ef5ba71b30f00801f',
    messagingSenderId: '1042179262286',
    projectId: 'homzes-e3fa3',
    storageBucket: 'homzes-e3fa3.firebasestorage.app',
    iosBundleId: 'com.example.homzesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASXaY-36shfdesVxpQdViJRTUleD8Ev3o',
    appId: '1:1042179262286:web:0fd72e0e2aa7004e00801f',
    messagingSenderId: '1042179262286',
    projectId: 'homzes-e3fa3',
    authDomain: 'homzes-e3fa3.firebaseapp.com',
    storageBucket: 'homzes-e3fa3.firebasestorage.app',
    measurementId: 'G-THFRG58JBQ',
  );
}
